/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Clases.Cliente;
import java.util.ArrayList;
import Clases.*;
import java.awt.Dimension;
import java.util.concurrent.Semaphore;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.event.AncestorEvent;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class main extends javax.swing.JFrame {

    ArrayList<Cliente> clientesGeneral, clientesEscritor;
    ArrayList<Despachador> despachadores;
    Despachador despachador1, despachador2, despachador3, despachador4, despachador5;
    int posicionGeneralY, posicionEscritorY, contadorLectores = 0;
    boolean lectorEnArea, escritorEnArea;
    Semaphore mutex = new Semaphore(1, true);

    public main() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        this.setSize(new Dimension(1069, 676));
        clientesGeneral = new ArrayList<Cliente>();
        clientesEscritor = new ArrayList<>();
        despachadores = new ArrayList<Despachador>();
        posicionGeneralY = 0;
        posicionEscritorY = 0;
        //lectorEnArea = false;
        escritorEnArea = false;

         rsscalelabel.RSScaleLabel.setScaleLabel(jLabelLectores, "src/img/lector2.png");
         rsscalelabel.RSScaleLabel.setScaleLabel(jLabelEscritores, "src/img/escritor1.png");
        
        despachador1 = new Despachador(panelCaja1, barraProgreso1);
        despachador2 = new Despachador(panelCaja2, barraProgreso2);
        despachador3 = new Despachador(panelCaja3, barraProgreso3);
        despachador4 = new Despachador(panelCaja4, barraProgreso4);
        despachador5 = new Despachador(panelCaja5, barraProgreso5);

        despachadores.add(despachador1);
        despachadores.add(despachador2);
        despachadores.add(despachador3);
        despachadores.add(despachador4);
        despachadores.add(despachador5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        barraProgreso1 = new javax.swing.JProgressBar();
        panelCaja1 = new javax.swing.JPanel();
        barraProgreso2 = new javax.swing.JProgressBar();
        panelCaja2 = new javax.swing.JPanel();
        panelCaja3 = new javax.swing.JPanel();
        barraProgreso3 = new javax.swing.JProgressBar();
        panelCaja4 = new javax.swing.JPanel();
        barraProgreso4 = new javax.swing.JProgressBar();
        panelCaja5 = new javax.swing.JPanel();
        barraProgreso5 = new javax.swing.JProgressBar();
        jLabelLectores = new javax.swing.JLabel();
        panelEsperaGeneral = new javax.swing.JPanel();
        jLabelEscritores = new javax.swing.JLabel();
        btnIngresarEscritor = new javax.swing.JButton();
        btnIngresarLector = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 224, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Despacho");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 903, 25));
        jPanel1.add(barraProgreso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 178, 18));

        panelCaja1.setBackground(new java.awt.Color(214, 224, 230));
        panelCaja1.setPreferredSize(new java.awt.Dimension(178, 129));

        javax.swing.GroupLayout panelCaja1Layout = new javax.swing.GroupLayout(panelCaja1);
        panelCaja1.setLayout(panelCaja1Layout);
        panelCaja1Layout.setHorizontalGroup(
            panelCaja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        panelCaja1Layout.setVerticalGroup(
            panelCaja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );

        jPanel1.add(panelCaja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));
        jPanel1.add(barraProgreso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 178, 18));

        panelCaja2.setBackground(new java.awt.Color(214, 224, 230));
        panelCaja2.setPreferredSize(new java.awt.Dimension(178, 129));

        javax.swing.GroupLayout panelCaja2Layout = new javax.swing.GroupLayout(panelCaja2);
        panelCaja2.setLayout(panelCaja2Layout);
        panelCaja2Layout.setHorizontalGroup(
            panelCaja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        panelCaja2Layout.setVerticalGroup(
            panelCaja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );

        jPanel1.add(panelCaja2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        panelCaja3.setBackground(new java.awt.Color(214, 224, 230));
        panelCaja3.setPreferredSize(new java.awt.Dimension(178, 129));

        javax.swing.GroupLayout panelCaja3Layout = new javax.swing.GroupLayout(panelCaja3);
        panelCaja3.setLayout(panelCaja3Layout);
        panelCaja3Layout.setHorizontalGroup(
            panelCaja3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        panelCaja3Layout.setVerticalGroup(
            panelCaja3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );

        jPanel1.add(panelCaja3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));
        jPanel1.add(barraProgreso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 178, -1));

        panelCaja4.setBackground(new java.awt.Color(214, 224, 230));
        panelCaja4.setPreferredSize(new java.awt.Dimension(178, 129));

        javax.swing.GroupLayout panelCaja4Layout = new javax.swing.GroupLayout(panelCaja4);
        panelCaja4.setLayout(panelCaja4Layout);
        panelCaja4Layout.setHorizontalGroup(
            panelCaja4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        panelCaja4Layout.setVerticalGroup(
            panelCaja4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );

        jPanel1.add(panelCaja4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, -1));
        jPanel1.add(barraProgreso4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 178, -1));

        panelCaja5.setBackground(new java.awt.Color(214, 224, 230));
        panelCaja5.setPreferredSize(new java.awt.Dimension(178, 129));

        javax.swing.GroupLayout panelCaja5Layout = new javax.swing.GroupLayout(panelCaja5);
        panelCaja5.setLayout(panelCaja5Layout);
        panelCaja5Layout.setHorizontalGroup(
            panelCaja5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        panelCaja5Layout.setVerticalGroup(
            panelCaja5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );

        jPanel1.add(panelCaja5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 178, -1));
        jPanel1.add(barraProgreso5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 178, -1));

        jLabelLectores.setBackground(new java.awt.Color(214, 224, 230));
        jPanel1.add(jLabelLectores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 266, 259));

        panelEsperaGeneral.setBackground(new java.awt.Color(214, 224, 230));
        panelEsperaGeneral.setPreferredSize(new java.awt.Dimension(178, 516));
        panelEsperaGeneral.setRequestFocusEnabled(false);

        javax.swing.GroupLayout panelEsperaGeneralLayout = new javax.swing.GroupLayout(panelEsperaGeneral);
        panelEsperaGeneral.setLayout(panelEsperaGeneralLayout);
        panelEsperaGeneralLayout.setHorizontalGroup(
            panelEsperaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        panelEsperaGeneralLayout.setVerticalGroup(
            panelEsperaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        jPanel1.add(panelEsperaGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, 381));
        jPanel1.add(jLabelEscritores, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 267, 279));

        btnIngresarEscritor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_ingresar-escritores.png"))); // NOI18N
        btnIngresarEscritor.setBorder(null);
        btnIngresarEscritor.setBorderPainted(false);
        btnIngresarEscritor.setContentAreaFilled(false);
        btnIngresarEscritor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarEscritorActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresarEscritor, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 550, 302, -1));

        btnIngresarLector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_ingresar-lectores.png"))); // NOI18N
        btnIngresarLector.setBorder(null);
        btnIngresarLector.setBorderPainted(false);
        btnIngresarLector.setContentAreaFilled(false);
        btnIngresarLector.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_ingresar-lectores.png"))); // NOI18N
        btnIngresarLector.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_ingresar-lectores.png"))); // NOI18N
        btnIngresarLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarLectorActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresarLector, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 318, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void desplazarCliente(JPanel panel, ArrayList<Cliente> clientes, int posicionY) {
        for (Cliente cliente : clientes) {
            int y = cliente.getLabel().getY();
            y -= 129;
            cliente.getLabel().setBounds(0, y, 178, 129);
        }
        panel.repaint();
        if (posicionY == 0) {
            posicionGeneralY -= 129;
        } else {
            posicionEscritorY -= 129;
        }

    }

    public int ingresarCliente(JPanel panel, Cliente cliente, ArrayList<Cliente> clientes, int posicionY) {
        /*Se verifica que el array es menor a cuatro, 
          por que es lo que cabe en el panel general, y en el panel de bloqueados
         */
        if (clientes.size() < 4) {
            /*Se modifica la posicion del label del cliente*/
            cliente.getLabel().setBounds(0, posicionY, 178, 129);
            //se agrega el label del cliente al panel 
            panel.add(cliente.getLabel());
            //se actuliza el panel para mostrar el label del cliente 
            panel.repaint();
            //se incrementa la posicion en Y, la cual s
            posicionY += 129;
            clientes.add(cliente);
        } else {
            JOptionPane.showMessageDialog(null, "Ya no hay espacion en la fila general", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return posicionY;
    }

    public void AtenderEscritor(JPanel panel, ArrayList<Cliente> clientes, int posicionY) {
        //recorremos el array de despachadores buscando uno que este libre con estado 0
        for (Despachador despachador : despachadores) {
            if (despachador.getEstado() == 0) {//verificamos el estado 
                //removemos del panel de espera general el cliente que este en la primera posicion
                try {
                     //rsscalelabel.RSScaleLabel.setScaleLabel(jLabelLector1, "src/img/lector.png");
                    mutex.acquire();
                } catch (InterruptedException ex) {
                    Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                }
                panel.remove(clientes.get(0).getLabel());
                //volvemos a pintar el panel
                
                panel.repaint();
                mutex.release();
                //le ingresamos al despachador el cliente 
                despachador.setCliente(clientes.get(0));
                //agragamos el label del cliente al panel del despachador 
                despachador.getPanel().add(despachador.getCliente().getLabel());
                //volvemos a pintar el panel del despachador 
                despachador.getPanel().repaint();
                //removemos de la lista de clientes el primer cliente 
                try {
                    mutex.acquire();
                } catch (InterruptedException ex) {
                    Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                }
                clientes.remove(0);
                //desplazamos los clientes una posicion
                desplazarCliente(panel, clientes, posicionY);
                mutex.release();
                //pones el estado del despachador en 1, lo que signfica que ahora esta ocupado
                despachador.setEstado(1);
                AtenderCliente atender = new AtenderCliente(despachador);
                atender.start();
                contadorLectores++;//aumenta el numero de lectores en el area critica
                break;
            }

        }
        //rsscalelabel.RSScaleLabel.setScaleLabel(jLabelLector1, "");

    }

    //Previo a atender clientes
    public void condiciondeAtender() {

        if (clientesGeneral.size() > 0) {//antes de atender debe de ver que existan clientes 
            if (clientesGeneral.get(0).getTipoCliente() == 0) { // si es un lector 
                if (escritorEnArea == false) {

                    AtenderEscritor(panelEsperaGeneral, clientesGeneral, 0);//atiende al lector
                    System.out.println("Mas contador: " + contadorLectores);
                }
            } else if (clientesGeneral.get(0).getTipoCliente() == 1) {//si es un escritor 
                System.out.println("entro");
                /*para atender a un escritor debe de ver que en el area critica 
                  no hayan ni lectores ni escritores
                 */
                if (contadorLectores == 0 && escritorEnArea == false) {
                    //atiende al escritor, lo pone en el area critica 
                    AtenderEscritor(panelEsperaGeneral, clientesGeneral, 0);
                    /*pone en verdadera la bandera de escritor en area critica
                     esto indica que hay un escritor en el area critica y no puede acceder 
                     ni un lector, ni un escritor 
                     */
                    escritorEnArea = true;
                }
                /*Este else es si existe algun proceso en el area critica
                  lo que va a hacer es mandarlo a bloqueado, lo cual seria lo cual seria 
                  el panel de la derecha, el de fila escritor bloqueado
                 */
            }
        } else {
            //JOptionPane.showMessageDialog(null, "No hay clientes para antender en el general", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void btnIngresarLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarLectorActionPerformed
        Cliente cliente = new Cliente(0);
        try {
            
            mutex.acquire();
           
        } catch (InterruptedException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
        posicionGeneralY = ingresarCliente(panelEsperaGeneral, cliente, clientesGeneral, posicionGeneralY);
        mutex.release();
        condiciondeAtender();
        
        System.out.println(posicionGeneralY);
    }//GEN-LAST:event_btnIngresarLectorActionPerformed

    private void btnIngresarEscritorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarEscritorActionPerformed
        Cliente cliente = new Cliente(1);
        try {
            mutex.acquire();
        } catch (InterruptedException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
        posicionGeneralY = ingresarCliente(panelEsperaGeneral, cliente, clientesGeneral, posicionGeneralY);
        mutex.release();
        condiciondeAtender();
        System.out.println(posicionGeneralY);
    }//GEN-LAST:event_btnIngresarEscritorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    public class AtenderCliente extends Thread {

        Despachador despachador;

        public AtenderCliente(Despachador despachador) {
            this.despachador = despachador;
        }

        @Override
        public void run() {
            for (int i = 1; i <= 100; i++) {
                try {
                    Thread.sleep(50);
                } catch (InterruptedException ex) {
                    java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                despachador.getBarra().setValue(i);
            }
            //Eliminamos el label del cliente del panel del despachador
            despachador.getPanel().remove(despachador.getCliente().getLabel());
            //repintamos el panele del despachador
            despachador.getPanel().repaint();
            //el estado del despachador vuelve a cero
            despachador.setEstado(0);
            //dejamos la barra de progreso igual a cero
            despachador.getBarra().setValue(0);
            //si hay mas de un lector se reduce
            if (contadorLectores > 0) {
                contadorLectores--;
            }
            if (escritorEnArea) {
                if (clientesEscritor.size() == 0) {
                    for (Despachador despachador : despachadores) {
                        if (despachador.getEstado() == 0) {
                            if (clientesGeneral.size() > 0) {
                                escritorEnArea = false;
                                if (clientesGeneral.get(0).getTipoCliente() == 0) {
                                    condiciondeAtender();
                                }
                            }
                        }
                    }
                }
            }
            System.out.println("Menos contador: " + contadorLectores);
            //si entro un escritor se pone en falso
            escritorEnArea = false;
            condiciondeAtender();

        }

    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso1;
    private javax.swing.JProgressBar barraProgreso2;
    private javax.swing.JProgressBar barraProgreso3;
    private javax.swing.JProgressBar barraProgreso4;
    private javax.swing.JProgressBar barraProgreso5;
    private javax.swing.JButton btnIngresarEscritor;
    private javax.swing.JButton btnIngresarLector;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEscritores;
    private javax.swing.JLabel jLabelLectores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelCaja1;
    private javax.swing.JPanel panelCaja2;
    private javax.swing.JPanel panelCaja3;
    private javax.swing.JPanel panelCaja4;
    private javax.swing.JPanel panelCaja5;
    private javax.swing.JPanel panelEsperaGeneral;
    // End of variables declaration//GEN-END:variables

}

